/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.tetris.tetrisapp;



/**
 *
 * @author António
 */
public class TetrisApp extends javax.swing.JFrame{

    /**
     * Creates new form TetrisApp
     */
    public TetrisApp() {
        initComponents();
        tetrisBoard2.getTimer().start();
        tetrisBoard2.setlblPontos(lblPontos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPontos = new javax.swing.JLabel();
        BotaoPausa = new javax.swing.JButton();
        BotaoContinuar = new javax.swing.JButton();
        BotaoSair = new javax.swing.JButton();
        tetrisBoard2 = new com.mycompany.tetris.pecas.TetrisBoard();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo Do Tetris");

        lblPontos.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lblPontos.setText("Pontuação:");

        BotaoPausa.setBackground(new java.awt.Color(255, 51, 51));
        BotaoPausa.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        BotaoPausa.setForeground(new java.awt.Color(255, 255, 255));
        BotaoPausa.setText("Pausa");
        BotaoPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPausaActionPerformed(evt);
            }
        });

        BotaoContinuar.setBackground(new java.awt.Color(255, 51, 51));
        BotaoContinuar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        BotaoContinuar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoContinuar.setText("Continuar");
        BotaoContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoContinuarActionPerformed(evt);
            }
        });

        BotaoSair.setBackground(new java.awt.Color(255, 51, 51));
        BotaoSair.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        BotaoSair.setForeground(new java.awt.Color(255, 255, 255));
        BotaoSair.setText("Sair do Jogo");
        BotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tetrisBoard2Layout = new javax.swing.GroupLayout(tetrisBoard2);
        tetrisBoard2.setLayout(tetrisBoard2Layout);
        tetrisBoard2Layout.setHorizontalGroup(
            tetrisBoard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        tetrisBoard2Layout.setVerticalGroup(
            tetrisBoard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblPontos)
                .addGap(104, 104, 104)
                .addComponent(tetrisBoard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoPausa, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lblPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(tetrisBoard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(BotaoPausa)
                        .addGap(46, 46, 46)
                        .addComponent(BotaoContinuar)
                        .addGap(44, 44, 44)
                        .addComponent(BotaoSair)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BotaoSairActionPerformed

    private void BotaoPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPausaActionPerformed
        // TODO add your handling code here:
        tetrisBoard2.stopTimer();
    }//GEN-LAST:event_BotaoPausaActionPerformed

    private void BotaoContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoContinuarActionPerformed
        // TODO add your handling code here:
        tetrisBoard2.restartTimer();
    }//GEN-LAST:event_BotaoContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TetrisApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TetrisApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TetrisApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TetrisApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TetrisApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoContinuar;
    private javax.swing.JButton BotaoPausa;
    private javax.swing.JButton BotaoSair;
    private javax.swing.JLabel lblPontos;
    private com.mycompany.tetris.pecas.TetrisBoard tetrisBoard2;
    // End of variables declaration//GEN-END:variables
}
